// generateImageMap.js
const fs = require('fs');
const path = require('path');
const assetsDir = path.join(__dirname, '../assets'); // adjust path
const outputFile = path.join(assetsDir, 'imageMap.js');

// Extensions to support
const exts = ['.png', '.jpg', '.jpeg', '.gif', '.webp'];

let imports = [];
let exportsMap = [];

fs.readdirSync(assetsDir).forEach(file => {
  const ext = path.extname(file).toLowerCase();
  if (exts.includes(ext)) {
    const name = path.basename(file, ext);
    const varName = name.replace(/[^a-zA-Z0-9_]/g, '_');
    imports.push(`const ${varName} = require('./${file}');`);
    exportsMap.push(`  "${name}": ${varName}`);
  }
});

const content = `// Auto-generated by generateImageMap.js
${imports.join('\n')}

export default {
${exportsMap.join(',\n')}
};
`;

fs.writeFileSync(outputFile, content, 'utf8');
console.log(`✅ Generated ${outputFile}`);
